version: "3"
services:
  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce:latest
    container_name: lowcoder
    ports:
      - "3000:3000"
      - "3443:3443"
    environment:
      LOWCODER_PUBLIC_URL: "http://localhost:3000/"
      LOWCODER_REDIS_ENABLED: "true"
      LOWCODER_MONGODB_ENABLED: "true"
      LOWCODER_MONGODB_EXPOSED: "false"
      LOWCODER_API_SERVICE_ENABLED: "true"
      LOWCODER_NODE_SERVICE_ENABLED: "true"
      LOWCODER_FRONTEND_ENABLED: "true"
      LOWCODER_PUID: "1000"
      LOWCODER_PGID: "1000"
      LOWCODER_MAX_ORGS_PER_USER: 100
      LOWCODER_MAX_MEMBERS_PER_ORG: 1000
      LOWCODER_MAX_GROUPS_PER_ORG: 100
      LOWCODER_MAX_APPS_PER_ORG: 1000
      LOWCODER_MAX_DEVELOPERS: 50
      LOWCODER_MONGODB_URL: "mongodb://localhost:27017/lowcoder?authSource=admin"
      LOWCODER_REDIS_URL: "redis://localhost:6379"
      LOWCODER_EMAIL_SIGNUP_ENABLED: "true"
      LOWCODER_EMAIL_AUTH_ENABLED: "true"
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: "true"
      LOWCODER_DB_ENCRYPTION_PASSWORD: "lowcoder.org"
      LOWCODER_DB_ENCRYPTION_SALT: "lowcoder.org"
      LOWCODER_CORS_DOMAINS: "*"
      LOWCODER_API_KEY_SECRET: "5a41b090758b39b226603177ef48d73ae9839dd458ccb7e66f7e7cc028d5a50b"
      LOWCODER_PLUGINS_DIR: "../plugins"
      LOWCODER_API_RATE_LIMIT: 50
      LOWCODER_API_SERVICE_URL: "http://localhost:8080"
      LOWCODER_NODE_SERVICE_URL: "http://localhost:6060"
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_WORKSPACE_MODE: SAAS
      LOWCODER_MARKETPLACE_PRIVATE_MODE: "true"
      LOWCODER_ADMIN_SMTP_HOST: localhost
      LOWCODER_ADMIN_SMTP_PORT: 587
      LOWCODER_ADMIN_SMTP_AUTH: "true"
      LOWCODER_ADMIN_SMTP_SSL_ENABLED: "false"
      LOWCODER_ADMIN_SMTP_STARTTLS_ENABLED: "true"
      LOWCODER_ADMIN_SMTP_STARTTLS_REQUIRED: "true"
      LOWCODER_EMAIL_NOTIFICATIONS_SENDER: info@localhost
      LOWCODER_SUPERUSER_USERNAME: admin@localhost
      LOWCODER_SUPERUSER_PASSWORD:
    volumes:
      - ./lowcoder-stacks:/lowcoder-stacks
      - ./lowcoder-stacks/assets:/lowcoder/assets
    restart: unless-stopped
