version: "3"
services:
  mongodb:
    image: "mongo:7.0"
    environment:
      MONGO_INITDB_DATABASE: lowcoder
      MONGO_INITDB_ROOT_USERNAME: lowcoder
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  lowcoder-api-service:
    image: lowcoderorg/lowcoder-ce-api-service:latest
    environment:
      LOWCODER_PUBLIC_URL: ${APP_URL}
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_MONGODB_URL: "mongodb://lowcoder:${MONGODB_PASSWORD}@mongodb/lowcoder?authSource=admin"
      LOWCODER_REDIS_URL: "redis://redis:6379"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_EMAIL_AUTH_ENABLED: ${EMAIL_AUTH_ENABLED:-true}
      LOWCODER_EMAIL_SIGNUP_ENABLED: ${EMAIL_SIGNUP_ENABLED:-true}
      LOWCODER_CREATE_WORKSPACE_ON_SIGNUP: ${CREATE_WORKSPACE_ON_SIGNUP:-true}
      LOWCODER_DB_ENCRYPTION_PASSWORD: ${DB_ENCRYPTION_PASSWORD}
      LOWCODER_DB_ENCRYPTION_SALT: ${DB_ENCRYPTION_SALT}
      LOWCODER_CORS_DOMAINS: "*"
      LOWCODER_MAX_ORGS_PER_USER: 100
      LOWCODER_MAX_MEMBERS_PER_ORG: 1000
      LOWCODER_MAX_GROUPS_PER_ORG: 100
      LOWCODER_MAX_APPS_PER_ORG: 1000
      LOWCODER_MAX_DEVELOPERS: 50
      LOWCODER_API_KEY_SECRET: ${API_KEY_SECRET}
      LOWCODER_PLUGINS_DIR: "../plugins"
      LOWCODER_API_RATE_LIMIT: 50
      LOWCODER_WORKSPACE_MODE: SAAS
      LOWCODER_MARKETPLACE_PRIVATE_MODE: "true"
      LOWCODER_ADMIN_SMTP_HOST: ${SMTP_HOST}
      LOWCODER_ADMIN_SMTP_PORT: ${SMTP_PORT:-587}
      LOWCODER_ADMIN_SMTP_USERNAME: ${SMTP_USERNAME}
      LOWCODER_ADMIN_SMTP_PASSWORD: ${SMTP_PASSWORD}
      LOWCODER_ADMIN_SMTP_AUTH: ${SMTP_AUTH:-true}
      LOWCODER_ADMIN_SMTP_SSL_ENABLED: ${SMTP_SSL:-false}
      LOWCODER_ADMIN_SMTP_STARTTLS_ENABLED: ${SMTP_STARTTLS:-true}
      LOWCODER_ADMIN_SMTP_STARTTLS_REQUIRED: ${SMTP_STARTTLS_REQUIRED:-true}
      LOWCODER_EMAIL_NOTIFICATIONS_SENDER: ${EMAIL_SENDER:-info@localhost}
      LOWCODER_SUPERUSER_USERNAME: ${ADMIN_EMAIL:-admin@localhost}
      LOWCODER_SUPERUSER_PASSWORD: ${ADMIN_PASSWORD}
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    volumes:
      - lowcoder_assets:/lowcoder/assets

  lowcoder-node-service:
    image: lowcoderorg/lowcoder-ce-node-service:latest
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
    restart: unless-stopped
    depends_on:
      - lowcoder-api-service

  lowcoder-frontend:
    image: lowcoderorg/lowcoder-ce-frontend:latest
    ports:
      - "${PORT:-3000}:3000"
    environment:
      LOWCODER_PUID: "9001"
      LOWCODER_PGID: "9001"
      LOWCODER_MAX_REQUEST_SIZE: 20m
      LOWCODER_MAX_QUERY_TIMEOUT: 120
      LOWCODER_API_SERVICE_URL: "http://lowcoder-api-service:8080"
      LOWCODER_NODE_SERVICE_URL: "http://lowcoder-node-service:6060"
    restart: unless-stopped
    depends_on:
      - lowcoder-node-service
      - lowcoder-api-service
    volumes:
      - lowcoder_assets:/lowcoder/assets

volumes:
  mongodb_data:
  redis_data:
  lowcoder_assets:
